subMenuBackButton = {
	"text": "Back",
	"icon": "fa-reply",
	"background": "linear-gradient(164deg, rgba(106,106,106,1) 0%, rgba(189,189,189,1) 100%)",
	"type": "menu",
	"target": "mainMenu",
}

menus = {
	"mainMenu":[
		{
			"text": "Talent",
			"icon": "fa-globe-europe",
			"background": "linear-gradient(164deg, rgba(16,106,28,1) 0%, rgba(93,186,118,1) 90%)",
			"type": "url",
			"target": "https://talent.capgemini.com/uk",
		},
		{
			"text": "WiFi Help",
			"icon": "fa-wifi",
			"background": "linear-gradient(155deg, rgba(40,40,40,1) 17%, rgba(112,112,112,1) 99%)",
			"type": "url",
			"target": "https://talent.capgemini.com/global/pages/about_us/global_functions/group_it/our_services/network/",
		},
		{
			"text": "My details",
			"icon": "fa-address-card",
			"background": "linear-gradient(164deg, rgba(98,87,32,1) 0%, rgba(255,115,0,1) 100%)",
			"type": "url",
			"target": "https://corporatedirectory.capgemini.com/MyDirectory/portals/std/index-portal.jsp?selresource=&resource=myDetails",
		},
		{
			"text": "DTX.net",
			"icon": "fa-business-time",
			"background": "linear-gradient(164deg, rgba(0,75,142,1) 15%, rgba(49,185,255,1) 100%)",
			"type": "url",
			"target": "https://missbhadtx03.corp.capgemini.com/DTX.NET/Summary.aspx",
		},
		{
			"text": "MyLearning",
			"icon": "fa-graduation-cap",
			"background": "linear-gradient(164deg, rgba(40,7,87,1) 0%, rgba(114,0,228,1) 100%)",
			"type": "url",
			"target": "https://mylearning.capgemini.com/",
		},
		{
			"text": "MyPath",
			"icon": "fa-route",
			"background": "linear-gradient(164deg, rgba(7,60,87,1) 0%, rgba(103,204,126,1) 100%)",
			"type": "url",
			"target": "https://myconnect.capgemini.com/sap/bc/ui5_ui5/sap/zmypath/index.html?sap-client=100",
		},
		{
			"text": "Egencia",
			"icon": "fa-plane-departure",
			"background": "linear-gradient(164deg, rgba(48,91,149,1) 0%, rgba(67,96,122,1) 74%)",
			"type": "url",
			"target": "https://www.egencia.co.uk/home/?locale=en_GB",
		},
		{
			"text": "Book hotel",
			"icon": "fa-door-open",
			"background": "linear-gradient(164deg, rgba(92,15,15,1) 0%, rgba(193,80,80,1) 100%)",
			"type": "page",
			"target": "search-hotels.html",
		},
		{
			"text": "MyExpenses",
			"icon": "fa-money-bill-wave",
			"background": "linear-gradient(164deg, rgba(120,3,84,1) 0%, rgba(255,0,0,1) 100%)",
			"type": "url",
			"target": "https://eu1.concursolutions.com/expense/client/default.asp",
		},
		{
			"text": "Other",
			"icon": "fa-wrench",
			"background": "linear-gradient(164deg, rgba(106,106,106,1) 0%, rgba(189,189,189,1) 100%)",
			"type": "menu",
			"target": "otherMenu",
		},
	],
	"otherMenu":[
		{
			"text": "Better DTX",
			"icon": "fa-check-double",
			"background": "linear-gradient(164deg, rgba(0,184,111,1) 0%, rgba(0,255,205,1) 100%)",
			"type": "url",
			"target": "https://chrome.google.com/webstore/detail/dtx-polyfiller/mbdlbjpimeeemdhkehileedfdemdlogk",
		},
		{
			"text": "MobilePass",
			"icon": "fa-key",
			"background": "linear-gradient(164deg, rgba(147,49,15,1) 0%, rgba(242,60,0,1) 100%)",
			"type": "url",
			"target": "https://selfportal.capgemini.com/",
		},
		{
			"text": "365 Web",
			"icon": "fa-file-upload",
			"background": "linear-gradient(164deg, rgba(15,92,51,1) 0%, rgba(80,193,157,1) 100%)",
			"type": "url",
			"target": "https://capgemini.sharepoint.com/sites/office365-portal",
		},
	],
}